package org.duancq90.pachong.area;

import java.io.IOException;
import lombok.extern.slf4j.Slf4j;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

@Slf4j
public class Index {

  public static void main(String[] args) throws IOException {

    Document document = Jsoup.parse(HTML);
    Elements elements = document.getElementsByClass("provincetr");

    elements.forEach(element -> {
      log.info("\nelement:{}", element.html());
      Elements as = element.getElementsByTag("a");
      as.forEach(a -> {
        String url = a.attr("href");
        log.info("\nid:{},name:{},url:{}",
            url.substring(0, url.indexOf(".")) + "0000000000", a.text(), url);
      });
    });
  }

  private final static String HTML ="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd\">\n"
      + "<HTML>\n"
      + "<HEAD>\n"
      + "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
      + "<TITLE>2020年统计用区划代码和城乡划分代码</TITLE>\n"
      + "<STYLE type=text/css>\n"
      + "\tBODY {MARGIN: 0px}BODY {FONT-SIZE: 12px}\n"
      + "\tTD {FONT-SIZE: 12px}\n"
      + "\tTH {FONT-SIZE: 12px}\n"
      + "\t.redBig {COLOR: #d00018; FONT-SIZE: 18px; FONT-WEIGHT: bold}\n"
      + "\t.STYLE3 a{COLOR: #fff; text-decoration:none;}\n"
      + "\t.STYLE5 {COLOR: #236fbe; FONT-WEIGHT: bold}\n"
      + "\t.content {LINE-HEIGHT: 1.5; FONT-SIZE: 10.4pt}\n"
      + "\t.tdPading {PADDING-LEFT: 30px}.blue {COLOR: #0000ff}\n"
      + "\t.STYLE6 {COLOR: #ffffff}\n"
      + "\t.a2 {LINE-HEIGHT: 1.5; COLOR: #2a6fbd; FONT-SIZE: 12px}\n"
      + "\ta2:link {LINE-HEIGHT: 1.5; COLOR: #2a6fbd; FONT-SIZE: 12px}\n"
      + "\ta2:hover {LINE-HEIGHT: 1.5; COLOR: #2a6fbd; FONT-SIZE: 12px; TEXT-DECORATION: underline}\n"
      + "\ta2:visited {LINE-HEIGHT: 1.5; COLOR: #2a6fbd; FONT-SIZE: 12px}\n"
      + "</STYLE>\n"
      + "<SCRIPT language=javascript>\n"
      + "function doZoom(size){document.getElementById('zoom').style.fontSize=size+'px';}\n"
      + "</SCRIPT>\n"
      + "<META name=GENERATOR content=\"MSHTML 8.00.7600.16700\">\n"
      + "</HEAD>\n"
      + "<BODY>\n"
      + "<TABLE border=0 cellSpacing=0 cellPadding=0 width=778 align=center>\n"
      + "<TBODY>\n"
      + "<TR><TD colSpan=2><IMG src=\"http://www.stats.gov.cn/images/banner.jpg\" width=778 height=135></TD></TR></TBODY></TABLE><MAP id=Map name=Map><AREA href=\"http://www.stats.gov.cn/english/\" shape=rect coords=277,4,328,18><AREA href=\"http://www.stats.gov.cn:82/\" shape=rect coords=181,4,236,18><AREA href=\"http://www.stats.gov.cn/\" shape=rect coords=85,4,140,17></MAP><TABLE border=0 cellSpacing=0 cellPadding=0 width=778 align=center><TBODY><TR><TD vAlign=top><TABLE style=\"MARGIN-TOP: 15px; MARGIN-BOTTOM: 18px\" border=0 cellSpacing=0 cellPadding=0 width=\"100%\" align=center><TBODY><TR><TD style=\" BACKGROUND-REPEAT: repeat-x; BACKGROUND-POSITION: 50% top\" background=images/topLine.gif align=right></TD></TR><TR><TD style=\" BACKGROUND-REPEAT: repeat-y; BACKGROUND-POSITION: right 50%\" vAlign=top background=images/rightBorder.gif><TABLE border=0 cellSpacing=0 cellPadding=0 width=\"100%\"><TBODY><TR><TD width=\"1%\" height=\"200\" vAlign=top>\n"
      + "<table class='provincetable' width=775 ><tr ><td colspan=8  height=1 style='FONT-SIZE: 5px' >&nbsp;</td></tr>\n"
      + "<tr class='provincehead'><td  colspan=8 align='center' style='FONT-SIZE: 16px' height=39 vAlign='center' background='images/tiao.jpg'>\n"
      + "<strong>关于更新全国统计用区划代码和城乡划分代码的公告</strong></td>\n"
      + "</tr>\t<tr >\n"
      + "  <td colspan=8  height=50 style='FONT-SIZE: 12px' > 　　为确保第七次全国人口普查顺利进行，2020年度全国统计用区划代码和城乡划分代码更新维护的标准时点为2020年6月30日。目前，已完成更新维护工作,现予公布。<br> \n"
      + " 　　2020年统计用区划代码和城乡划分代码依据国务院批复同意的《关于统计上划分城乡的规定》（国函〔2008〕60号）及国家统计局印发的《统计用区划代码和城乡划分代码编制规则》（国统字〔2009〕91号）编制。<br> \n"
      + " 　　此次发布内容为2020年全国统计用区划代码（12位）和城乡分类代码（3位），地域范围为国家统计局开展统计调查的全国31个省、自治区、直辖市，未包括我国台湾省、香港特别行政区、澳门特别行政区。<br> \n"
      + " 　　《关于统计上划分城乡的规定》指出：“本规定作为统计上划分城乡的依据，不改变现有的行政区划、隶属关系、管理权限和机构编制，以及土地规划、城乡规划等有关规定”。统计用区划代码和城乡划分代码用于统计工作，需要在其他工作中使用时，请务必结合有关实际情况。<br> \n"
      + "</td>\n"
      + "</tr>\n"
      + "<tr class='provincetr'><td><a href='11.html'>北京市<br/></a></td><td><a href='12.html'>天津市<br/></a></td><td><a href='13.html'>河北省<br/></a></td><td><a href='14.html'>山西省<br/></a></td><td><a href='15.html'>内蒙古自治区<br/></a></td><td><a href='21.html'>辽宁省<br/></a></td><td><a href='22.html'>吉林省<br/></a></td><td><a href='23.html'>黑龙江省<br/></a></td></tr><tr class='provincetr'><td><a href='31.html'>上海市<br/></a></td><td><a href='32.html'>江苏省<br/></a></td><td><a href='33.html'>浙江省<br/></a></td><td><a href='34.html'>安徽省<br/></a></td><td><a href='35.html'>福建省<br/></a></td><td><a href='36.html'>江西省<br/></a></td><td><a href='37.html'>山东省<br/></a></td><td><a href='41.html'>河南省<br/></a></td></tr><tr class='provincetr'><td><a href='42.html'>湖北省<br/></a></td><td><a href='43.html'>湖南省<br/></a></td><td><a href='44.html'>广东省<br/></a></td><td><a href='45.html'>广西壮族自治区<br/></a></td><td><a href='46.html'>海南省<br/></a></td><td><a href='50.html'>重庆市<br/></a></td><td><a href='51.html'>四川省<br/></a></td><td><a href='52.html'>贵州省<br/></a></td></tr><tr class='provincetr'><td><a href='53.html'>云南省<br/></a></td><td><a href='54.html'>西藏自治区<br/></a></td><td><a href='61.html'>陕西省<br/></a></td><td><a href='62.html'>甘肃省<br/></a></td><td><a href='63.html'>青海省<br/></a></td><td><a href='64.html'>宁夏回族自治区<br/></a></td><td><a href='65.html'>新疆维吾尔自治区<br/></a></td><td><br/></td></tr>\n"
      + "</table>\n"
      + "</TD>\n"
      + "</TR>\n"
      + "</TBODY>\n"
      + "</TABLE>\n"
      + "</TD>\n"
      + "</TR>\n"
      + "<TR>\n"
      + "<TD style=\"BACKGROUND-REPEAT: repeat-x; BACKGROUND-POSITION: 50% top\"          background=images/borderBottom.gif>\n"
      + "</TD></TR></TBODY>\n"
      + "</TABLE></TD></TR>  <TR>    <TD bgColor=#e2eefc height=2></TD></TR>  <TR>\n"
      + "<TD class=STYLE3 height=60>\n"
      + "<DIV align=center style=\"background-color:#1E67A7; height:75px; color:#fff;\"><br/>\n"
      + "版权所有：国家统计局　　<A class=STYLE3       href=\"http://www.miibeian.gov.cn/\"       target=_blank>京ICP备05034670号</A><BR><BR>地址：北京市西城区月坛南街57号（100826）<BR></DIV></TD></TR></TBODY></TABLE></BODY></HTML>\n"
      + "\n"
      + "17:17:33.736 [main] INFO org.duancq90.pachong.main.Area - document:<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd\">\n"
      + "<html> \n"
      + " <head> \n"
      + "  <meta content=\"text/html; charset=gb2312\" http-equiv=\"Content-Type\"> \n"
      + "  <title>2020年统计用区划代码和城乡划分代码</title> \n"
      + "  <style type=\"text/css\">\n"
      + "\tBODY {MARGIN: 0px}BODY {FONT-SIZE: 12px}\n"
      + "\tTD {FONT-SIZE: 12px}\n"
      + "\tTH {FONT-SIZE: 12px}\n"
      + "\t.redBig {COLOR: #d00018; FONT-SIZE: 18px; FONT-WEIGHT: bold}\n"
      + "\t.STYLE3 a{COLOR: #fff; text-decoration:none;}\n"
      + "\t.STYLE5 {COLOR: #236fbe; FONT-WEIGHT: bold}\n"
      + "\t.content {LINE-HEIGHT: 1.5; FONT-SIZE: 10.4pt}\n"
      + "\t.tdPading {PADDING-LEFT: 30px}.blue {COLOR: #0000ff}\n"
      + "\t.STYLE6 {COLOR: #ffffff}\n"
      + "\t.a2 {LINE-HEIGHT: 1.5; COLOR: #2a6fbd; FONT-SIZE: 12px}\n"
      + "\ta2:link {LINE-HEIGHT: 1.5; COLOR: #2a6fbd; FONT-SIZE: 12px}\n"
      + "\ta2:hover {LINE-HEIGHT: 1.5; COLOR: #2a6fbd; FONT-SIZE: 12px; TEXT-DECORATION: underline}\n"
      + "\ta2:visited {LINE-HEIGHT: 1.5; COLOR: #2a6fbd; FONT-SIZE: 12px}\n"
      + "</style> \n"
      + "  <script language=\"javascript\">\n"
      + "function doZoom(size){document.getElementById('zoom').style.fontSize=size+'px';}\n"
      + "</script> \n"
      + "  <meta name=\"GENERATOR\" content=\"MSHTML 8.00.7600.16700\"> \n"
      + " </head> \n"
      + " <body> \n"
      + "  <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"778\" align=\"center\"> \n"
      + "   <tbody> \n"
      + "    <tr>\n"
      + "     <td colspan=\"2\"><img src=\"http://www.stats.gov.cn/images/banner.jpg\" width=\"778\" height=\"135\"></td>\n"
      + "    </tr>\n"
      + "   </tbody>\n"
      + "  </table><map id=\"Map\" name=\"Map\"><area href=\"http://www.stats.gov.cn/english/\" shape=\"rect\" coords=\"277,4,328,18\"><area href=\"http://www.stats.gov.cn:82/\" shape=\"rect\" coords=\"181,4,236,18\"><area href=\"http://www.stats.gov.cn/\" shape=\"rect\" coords=\"85,4,140,17\"></map>\n"
      + "  <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"778\" align=\"center\">\n"
      + "   <tbody>\n"
      + "    <tr>\n"
      + "     <td valign=\"top\">\n"
      + "      <table style=\"MARGIN-TOP: 15px; MARGIN-BOTTOM: 18px\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" align=\"center\">\n"
      + "       <tbody>\n"
      + "        <tr>\n"
      + "         <td style=\" BACKGROUND-REPEAT: repeat-x; BACKGROUND-POSITION: 50% top\" background=\"images/topLine.gif\" align=\"right\"></td>\n"
      + "        </tr>\n"
      + "        <tr>\n"
      + "         <td style=\" BACKGROUND-REPEAT: repeat-y; BACKGROUND-POSITION: right 50%\" valign=\"top\" background=\"images/rightBorder.gif\">\n"
      + "          <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\n"
      + "           <tbody>\n"
      + "            <tr>\n"
      + "             <td width=\"1%\" height=\"200\" valign=\"top\"> \n"
      + "              <table class=\"provincetable\" width=\"775\">\n"
      + "               <tbody>\n"
      + "                <tr>\n"
      + "                 <td colspan=\"8\" height=\"1\" style=\"FONT-SIZE: 5px\">&nbsp;</td>\n"
      + "                </tr> \n"
      + "                <tr class=\"provincehead\">\n"
      + "                 <td colspan=\"8\" align=\"center\" style=\"FONT-SIZE: 16px\" height=\"39\" valign=\"center\" background=\"images/tiao.jpg\"> <strong>关于更新全国统计用区划代码和城乡划分代码的公告</strong></td> \n"
      + "                </tr> \n"
      + "                <tr> \n"
      + "                 <td colspan=\"8\" height=\"50\" style=\"FONT-SIZE: 12px\"> 　　为确保第七次全国人口普查顺利进行，2020年度全国统计用区划代码和城乡划分代码更新维护的标准时点为2020年6月30日。目前，已完成更新维护工作,现予公布。<br> 　　2020年统计用区划代码和城乡划分代码依据国务院批复同意的《关于统计上划分城乡的规定》（国函〔2008〕60号）及国家统计局印发的《统计用区划代码和城乡划分代码编制规则》（国统字〔2009〕91号）编制。<br> 　　此次发布内容为2020年全国统计用区划代码（12位）和城乡分类代码（3位），地域范围为国家统计局开展统计调查的全国31个省、自治区、直辖市，未包括我国台湾省、香港特别行政区、澳门特别行政区。<br> 　　《关于统计上划分城乡的规定》指出：“本规定作为统计上划分城乡的依据，不改变现有的行政区划、隶属关系、管理权限和机构编制，以及土地规划、城乡规划等有关规定”。统计用区划代码和城乡划分代码用于统计工作，需要在其他工作中使用时，请务必结合有关实际情况。<br> </td> \n"
      + "                </tr> \n"
      + "                <tr class=\"provincetr\">\n"
      + "                 <td><a href=\"11.html\">北京市<br></a></td>\n"
      + "                 <td><a href=\"12.html\">天津市<br></a></td>\n"
      + "                 <td><a href=\"13.html\">河北省<br></a></td>\n"
      + "                 <td><a href=\"14.html\">山西省<br></a></td>\n"
      + "                 <td><a href=\"15.html\">内蒙古自治区<br></a></td>\n"
      + "                 <td><a href=\"21.html\">辽宁省<br></a></td>\n"
      + "                 <td><a href=\"22.html\">吉林省<br></a></td>\n"
      + "                 <td><a href=\"23.html\">黑龙江省<br></a></td>\n"
      + "                </tr>\n"
      + "                <tr class=\"provincetr\">\n"
      + "                 <td><a href=\"31.html\">上海市<br></a></td>\n"
      + "                 <td><a href=\"32.html\">江苏省<br></a></td>\n"
      + "                 <td><a href=\"33.html\">浙江省<br></a></td>\n"
      + "                 <td><a href=\"34.html\">安徽省<br></a></td>\n"
      + "                 <td><a href=\"35.html\">福建省<br></a></td>\n"
      + "                 <td><a href=\"36.html\">江西省<br></a></td>\n"
      + "                 <td><a href=\"37.html\">山东省<br></a></td>\n"
      + "                 <td><a href=\"41.html\">河南省<br></a></td>\n"
      + "                </tr>\n"
      + "                <tr class=\"provincetr\">\n"
      + "                 <td><a href=\"42.html\">湖北省<br></a></td>\n"
      + "                 <td><a href=\"43.html\">湖南省<br></a></td>\n"
      + "                 <td><a href=\"44.html\">广东省<br></a></td>\n"
      + "                 <td><a href=\"45.html\">广西壮族自治区<br></a></td>\n"
      + "                 <td><a href=\"46.html\">海南省<br></a></td>\n"
      + "                 <td><a href=\"50.html\">重庆市<br></a></td>\n"
      + "                 <td><a href=\"51.html\">四川省<br></a></td>\n"
      + "                 <td><a href=\"52.html\">贵州省<br></a></td>\n"
      + "                </tr>\n"
      + "                <tr class=\"provincetr\">\n"
      + "                 <td><a href=\"53.html\">云南省<br></a></td>\n"
      + "                 <td><a href=\"54.html\">西藏自治区<br></a></td>\n"
      + "                 <td><a href=\"61.html\">陕西省<br></a></td>\n"
      + "                 <td><a href=\"62.html\">甘肃省<br></a></td>\n"
      + "                 <td><a href=\"63.html\">青海省<br></a></td>\n"
      + "                 <td><a href=\"64.html\">宁夏回族自治区<br></a></td>\n"
      + "                 <td><a href=\"65.html\">新疆维吾尔自治区<br></a></td>\n"
      + "                 <td><br></td>\n"
      + "                </tr> \n"
      + "               </tbody>\n"
      + "              </table> </td> \n"
      + "            </tr> \n"
      + "           </tbody> \n"
      + "          </table> </td> \n"
      + "        </tr> \n"
      + "        <tr> \n"
      + "         <td style=\"BACKGROUND-REPEAT: repeat-x; BACKGROUND-POSITION: 50% top\" background=\"images/borderBottom.gif\"> </td>\n"
      + "        </tr>\n"
      + "       </tbody> \n"
      + "      </table></td>\n"
      + "    </tr> \n"
      + "    <tr> \n"
      + "     <td bgcolor=\"#e2eefc\" height=\"2\"></td>\n"
      + "    </tr> \n"
      + "    <tr> \n"
      + "     <td class=\"STYLE3\" height=\"60\"> \n"
      + "      <div align=\"center\" style=\"background-color:#1E67A7; height:75px; color:#fff;\">\n"
      + "       <br> 版权所有：国家统计局　　<a class=\"STYLE3\" href=\"http://www.miibeian.gov.cn/\" target=\"_blank\">京ICP备05034670号</a>\n"
      + "       <br>\n"
      + "       <br>地址：北京市西城区月坛南街57号（100826）\n"
      + "       <br>\n"
      + "      </div></td>\n"
      + "    </tr>\n"
      + "   </tbody>\n"
      + "  </table>\n"
      + " </body>\n"
      + "</html>";

  private static void sleep() {
    try {
      Thread.sleep(3 * 60 * 1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
}
